# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
---
version: 2
updates:
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    ignore:
      # TODO https://github.com/jenkinsci/plugin-pom/issues/936 delete when baseline is 2.459+ -->
      - dependency-name: "jakarta.servlet:jakarta.servlet-api"
        versions: [">=5.0.0"]
      - dependency-name: "org.jenkins-ci.main:jenkins-bom"
      - dependency-name: "org.jenkins-ci.main:jenkins-core"
      - dependency-name: "org.jenkins-ci.main:jenkins-war"
